### ISSUE TITLE
Plugin fails, no explanation

### ISSUE THREAD

**Issue by pcav** [sourcepole/qgis-instantprint-plugin#2]
Plugin fails to produce an output, with a message from composer (La stampa della composizione non è riuscita.). Tested with pdf and jpeg.

**Comment by manisandro** [comment]
What version of QGIS did you use? Can you provide a project with which the issue is reproducible? I cannot reproduce it with the latest master.

**Comment by pcav** [comment]
2.8.0 and 2.8.1. No attacments on GH, unfortunately. I can send you a project in private.

**Comment by manisandro** [comment]
That would be helpful, thanks.

**Comment by pcav** [comment]
Tried with a supersimple project (one vector layer, one composer), still fails.

**Comment by manisandro** [comment]
The functions which can fail are `QgsComposition::exportAsPDF` and `QgsComposition::printPageAsRaster` (and the unhelpful error message is simply because those functions don't provide me with more to report). Does saving from the composer window work?

**Comment by pcav** [comment]
Yes

**Comment by manisandro** [comment]
On which platform/arch can you reproduce this and, unless you compiled qgis yourself, which package did you use?

**Comment by pcav** [comment]
Debian Sid, QGIS 2.8.1.
Thanks.
