### ISSUE TITLE
icon issue

### ISSUE THREAD

**Issue by geosmiles** [sourcepole/qgis-instantprint-plugin#4]
I've found in QGIS 2.8, that after using the instant print plugin (which is very cool) the mouse icons remains as the pan drag icon, irrespective of the icon chosen (identify feature, add feature etc). 

Si

**Comment by manisandro** [comment]
Indeed, looks like something changed recently in QGIS, will need to look into it.

**Comment by manisandro** [comment]
1.0.2 released

**Comment by geosmiles** [comment]
Cheers :-)
